// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewProject struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	OwnerEmail  string `json:"ownerEmail"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
